-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Glass panel behind

hl.config({
    shape = {
        size = { 600, 100 },
        rounding = 18,
        color = lock_glass,
        -- glass tint (adjust alpha to taste)
        border_size = 2,
        border_color = { "rgba(255", 255, 255, "0.08)" },
        -- subtle rim highlight
        position = { 100, -475 },
        halign = "center",
        valign = "center",
        shadow_passes = 2,
        shadow_size = 14,
        shadow_color = { "rgba(0", 0, 0, "0.35)" },
        zindex = 0,
    },
})
-- NOTE: Section 'shape' may be a plugin or custom section; verify the output

-- Battery module anchor under the pane

-- (tweak these)

local bat_x = 90

local bat_y = -475

-- Force regeneration of the fill shape using the SAME anchor as the container pill

-- (invisible label; runs every 5s)

hl.config({
    label = {
        text = "cmd[update:5000] /usr/bin/env LOCK_BATT_PART=gen BAT_X=90 BAT_Y=-475 BAR_W=425 BAR_H=18 PAD=2 /home/kazuki/.config/hypr/scripts/lock-battery.sh",
        font_family = lock_font,
        font_size = 1,
        color = { "rgba(0", 0, 0, "0.0)" },
        position = { 0, 9999 },
        halign = "center",
        valign = "center",
        zindex = 1,
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Container pill (back layer) - VERY light tint or transparent

hl.config({
    shape = {
        size = { 425, 18 },
        rounding = 9,
        color = { "rgba(0", 0, 0, "0.00)" },
        -- important: no dark overlay on the fill
        border_size = 2,
        border_color = { "rgba(255", 255, 255, "0.10)" },
        position = { 90, -475 },
        halign = "center",
        valign = "center",
        zindex = 1,
    },
})
-- NOTE: Section 'shape' may be a plugin or custom section; verify the output

-- Fill pill (generated by script)

-- source = /home/kazuki/.cache/hyprlock/battery-fill.conf -> requires manual conversion
-- local battery-fill = require("battery-fill")
-- TODO: convert /home/kazuki/.cache/hyprlock/battery-fill.conf to .lua and use require()

-- Front rim (border only) - keeps glassy edge visible on top

hl.config({
    shape = {
        size = { 425, 18 },
        rounding = 9,
        color = { "rgba(0", 0, 0, "0.00)" },
        -- border-only overlay
        border_size = 2,
        border_color = { "rgba(255", 255, 255, "0.8)" },
        position = { 90, -475 },
        halign = "center",
        valign = "center",
        zindex = 2,
    },
})
-- NOTE: Section 'shape' may be a plugin or custom section; verify the output

-- Icon + bolt + percent on top (optional)

hl.config({
    label = {
        text = "cmd[update:5000] /usr/bin/env LOCK_BATT_PART=icon /home/kazuki/.config/hypr/scripts/lock-battery.sh",
        font_family = "CaskaydiaCove Nerd Font Mono",
        font_size = 60,
        color = lock_textalt,
        position = { -165, -475 },
        halign = "center",
        valign = "center",
        zindex = 1,
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

hl.config({
    label = {
        text = "cmd[update:5000] /usr/bin/env LOCK_BATT_PART=bolt /home/kazuki/.config/hypr/scripts/lock-battery.sh",
        font_family = "JetBrainsMono Nerd Font",
        font_size = 50,
        color = { "rgba(120", 255, 140, "0.8)" },
        position = { -165, -475 },
        halign = "center",
        valign = "center",
        zindex = 2,
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

hl.config({
    label = {
        text = "cmd[update:5000] /usr/bin/env LOCK_BATT_PART=pct /home/kazuki/.config/hypr/scripts/lock-battery.sh",
        font_family = lock_font,
        font_size = 24,
        color = lock_text,
        position = { 350, -475 },
        halign = "center",
        valign = "center",
        zindex = 1,
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output
