-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Glass panel behind now playing

hl.config({
    shape = {
        size = { 500, 100 },
        rounding = 18,
        color = lock_glass,
        -- glass tint (adjust alpha to taste)
        border_size = 2,
        border_color = { "rgba(255", 255, 255, "0.08)" },
        -- subtle rim highlight
        position = { -500, -475 },
        halign = "center",
        valign = "center",
        shadow_passes = 2,
        shadow_size = 14,
        shadow_color = { "rgba(0", 0, 0, "0.35)" },
        zindex = 0,
    },
})
-- NOTE: Section 'shape' may be a plugin or custom section; verify the output

-- Source icon (bigger, accent)

hl.config({
    label = {
        text = "cmd[update:1000] /usr/bin/env LOCK_NOW_PART=icon /home/kazuki/.config/hypr/scripts/lock-nowplaying.sh",
        font_family = "CaskaydiaCove Nerd Font Mono",
        font_size = 60,
        color = lock_textalt,
        position = { -700, -470 },
        halign = "center",
        valign = "center",
        zindex = 1,
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Track line (normal)

hl.config({
    label = {
        text = "cmd[update:1000] /usr/bin/env LOCK_NOW_PART=text /home/kazuki/.config/hypr/scripts/lock-nowplaying.sh",
        font_family = lock_font,
        font_size = 30,
        color = lock_text,
        position = { -475, -475 },
        halign = "center",
        valign = "center",
        zindex = 1,
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output
