-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Glass panel behind

hl.config({
    shape = {
        size = { 250, 100 },
        rounding = 18,
        color = lock_glass,
        -- glass tint (adjust alpha to taste)
        border_size = 2,
        border_color = { "rgba(255", 255, 255, "0.08)" },
        -- subtle rim highlight
        position = { 575, -475 },
        halign = "center",
        valign = "center",
        shadow_passes = 2,
        shadow_size = 14,
        shadow_color = { "rgba(0", 0, 0, "0.35)" },
        zindex = 0,
    },
})
-- NOTE: Section 'shape' may be a plugin or custom section; verify the output

local glyph_x = 500

local glyph_y = -475

local temp_size = 40

local glyph_size = 80

local temp_x = 625

local temp_y = -475

-- Sunny (orange)

hl.config({
    label = {
        text = "cmd[update:30000] /usr/bin/env LOCK_WEATHER_PART=sunny /home/kazuki/.config/weather/weather-read.sh",
        font_family = "CaskaydiaCove Nerd Font Mono",
        font_size = 80,
        color = { "rgba(244", 163, 64, "1.0)" },
        position = { 500, -475 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Cloudy (white)

hl.config({
    label = {
        text = "cmd[update:30000] /usr/bin/env LOCK_WEATHER_PART=cloudy /home/kazuki/.config/weather/weather-read.sh",
        font_family = "CaskaydiaCove Nerd Font Mono",
        font_size = 80,
        color = { "rgba(235", 235, 235, "1.0)" },
        position = { 500, -475 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Rain (blue)

hl.config({
    label = {
        text = "cmd[update:30000] /usr/bin/env LOCK_WEATHER_PART=rain /home/kazuki/.config/weather/weather-read.sh",
        font_family = "CaskaydiaCove Nerd Font Mono",
        font_size = 80,
        color = { "rgba(120", 180, 255, "1.0)" },
        position = { 500, -475 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Snow (white-blue)

hl.config({
    label = {
        text = "cmd[update:30000] /usr/bin/env LOCK_WEATHER_PART=snow /home/kazuki/.config/weather/weather-read.sh",
        font_family = "CaskaydiaCove Nerd Font Mono",
        font_size = 80,
        color = { "rgba(200", 230, 255, "1.0)" },
        position = { 500, -475 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Temperature (text)

hl.config({
    label = {
        text = "cmd[update:30000] /usr/bin/env LOCK_WEATHER_PART=temp /home/kazuki/.config/weather/weather-read.sh",
        font_family = lock_font,
        font_size = 40,
        color = lock_text,
        position = { 625, -475 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output
