[General]
type=sddm-theme
MainScript=Main.qml
ConfigFile=theme.conf
AuthError=Authentication failed
AuthMessage=Password

[users]
MaximumUid=60000
MinimumUid=1000
HideUsers=
HideShells=/sbin/nologin,/bin/false,/usr/bin/nologin

[greeter]
NumLock=on
