general {
    col.active_border = rgba(ca2b4bff) rgba(d57bc7ff) rgba(fff9a5ff)
    col.inactive_border = rgba(7a1e33ff) rgba(3b0f19ff)
    border_size = 4
}

decoration {
    rounding = 8

    shadow {
        enabled = true
        range = 10
        render_power = 3
        color = rgba(fff9a5ff)
        color_inactive = rgba(00000055)
    }
}
