# Colorscheme for Kitty

foreground            #F6E7D7
background            #2E3440
selection_foreground  #000000
selection_background  #FFFACD
url_color             #C83A5C
cursor                #E05A78

# Character Colorscheme for Kitty


# black
color0   #3B4252
color8   #4C566A

# red
color1   #E05A78
color9   #E05A78

# green
color2   #A3BE8C
color10  #A3BE8C

# yellow
color3   #fff9a5
color11  #FFE89A

# blue
color4  #E05A78
color12 #C83A5C

# magenta
color5   #e693d9
color13  #e693d9

# cyan
color6   #88C0D0
color14  #8FBCBB

# white
color7   #E5E9F0
color15  #ECEFF4
