-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    background = {
        path = lock_bg,
        blur_size = 8,
        blur_passes = 3,
        -- optional: keep conservative on older builds
        noise = 0.02,
        contrast = 1.05,
        brightness = 0.6,
    },
})
-- NOTE: Section 'background' may be a plugin or custom section; verify the output
