-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Glass pane

hl.config({
    shape = {
        size = { 1020, 760 },
        rounding = 26,
        color = lock_glass,
        border_size = 3,
        border_color = lock_accent,
        position = { 0, 0 },
        halign = "center",
        valign = "center",
        shadow_passes = 3,
        shadow_size = 18,
        shadow_color = lock_glow,
        zindex = 0,
    },
})
-- NOTE: Section 'shape' may be a plugin or custom section; verify the output

-- Hostname under the logo

-- Host icon (accent)

hl.config({
    label = {
        text = "󰍹",
        font_family = "CaskaydiaCove Nerd Font Mono",
        font_size = 80,
        color = lock_textalt,
        position = { -85, 225 },
        halign = "center",
        valign = "center",
        zindex = 1,
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Hostname text

hl.config({
    label = {
        text = "cmd[update:60000] /usr/bin/hostname",
        font_family = lock_font,
        font_size = 40,
        color = lock_text,
        position = { 55, 225 },
        halign = "center",
        valign = "center",
        zindex = 1,
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- User row above password field (icon + username)

-- User icon (accent)

hl.config({
    label = {
        text = "",
        font_family = "CaskaydiaCove Nerd Font Mono",
        font_size = 100,
        color = lock_textalt,
        position = { -315, 50 },
        halign = "center",
        valign = "center",
        zindex = 1,
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Username text

hl.config({
    label = {
        text = "cmd[update:60000] /usr/bin/whoami",
        font_family = lock_font,
        font_size = 60,
        color = lock_text,
        position = { -135, 50 },
        halign = "center",
        valign = "center",
        zindex = 1,
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Login field inside the pane

hl.config({
    input-field = {
        size = { 700, 106 },
        rounding = 18,
        position = { 0, -150 },
        halign = "center",
        valign = "center",
        inner_color = lock_field,
        font_color = lock_text,
        font_family = lock_font,
        font_size = 20,
        outline_thickness = 3,
        outer_color = lock_accent,
        placeholder_text = "Enter Password",
        dots_spacing = 0.25,
        dots_center = true,
        fade_on_empty = false,
    },
})
-- NOTE: Section 'input-field' may be a plugin or custom section; verify the output

-- Glass panel behind image

hl.config({
    shape = {
        size = { 425, 200 },
        rounding = 18,
        color = lock_imageback,
        -- glass tint (adjust alpha to taste)
        border_size = 2,
        border_color = { "rgba(255", 255, 255, "0.08)" },
        -- subtle rim highlight
        position = { 0, 375 },
        halign = "center",
        valign = "center",
        shadow_passes = 2,
        shadow_size = 14,
        shadow_color = { "rgba(0", 0, 0, "0.35)" },
        zindex = 9,
    },
})
-- NOTE: Section 'shape' may be a plugin or custom section; verify the output

-- OS/Omarchy logo overlapping the pane border

hl.config({
    image = {
        path = lock_logo,
        size = 200,
        rounding = 18,
        border_size = 3,
        border_color = lock_accent,
        position = { 0, 375 },
        halign = "center",
        valign = "center",
        zindex = 10,
    },
})
-- NOTE: Section 'image' may be a plugin or custom section; verify the output
