-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    label = {
        text = "cmd[update:1000] /home/kazuki/.config/hypr/scripts/lock-time.sh",
        font_family = lock_font,
        font_size = 200,
        color = { "rgba(235", 235, 235, "1.0)" },
        position = { 0, 750 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

hl.config({
    label = {
        text = "cmd[update:1000] /home/kazuki/.config/hypr/scripts/lock-date.sh",
        font_family = lock_font,
        font_size = 70,
        color = { "rgba(235", 235, 235, "0.92)" },
        position = { 0, 575 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output
