-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- source = ~/.config/hypr/assets/hyprlock/widgets/weather.conf -> requires manual conversion
-- local weather = require("weather")
-- TODO: convert ~/.config/hypr/assets/hyprlock/widgets/weather.conf to .lua and use require()

-- source = ~/.config/hypr/assets/hyprlock/widgets/nowplaying.conf -> requires manual conversion
-- local nowplaying = require("nowplaying")
-- TODO: convert ~/.config/hypr/assets/hyprlock/widgets/nowplaying.conf to .lua and use require()

-- source = ~/.config/hypr/assets/hyprlock/widgets/battery.conf -> requires manual conversion
-- local battery = require("battery")
-- TODO: convert ~/.config/hypr/assets/hyprlock/widgets/battery.conf to .lua and use require()
